name: Deploy React App to Cloud Run

on:
  push:
    paths:
      - 'React/**' # Trigger only when changes occur in the React folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker
      run: gcloud auth configure-docker
      
    - name: Authenticate Docker with Google Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        cd React
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/YOUR_REPOSITORY_NAME/react-app .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/YOUR_REPOSITORY_NAME/react-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy react-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
